 
import "./globals.css";  
import { Providers } from "./provider";
import { NextAuthProvider } from "./Providers"; 

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }) {
  return (
    <html>
      <head />
      <body>
        <NextAuthProvider session={session}>
          <Providers>{children}</Providers>
        </NextAuthProvider>
      </body>
    </html>
  );
}